"""initial Manabi schema

Revision ID: fddc8c6de4ce
Revises:
"""
from alembic import op
import sqlalchemy as sa


revision = 'fddc8c6de4ce'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('exams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('level', sa.String(length=2), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('source_metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level', 'source_id')
    )
    op.create_index(op.f('ix_exams_level'), 'exams', ['level'], unique=False)
    op.create_table('import_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_types',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('name_zh', sa.String(length=64), nullable=False),
    sa.Column('name_ja', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_types_category'), 'question_types', ['category'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('prompt', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('level', sa.String(length=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('materials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('translation', sa.JSON(), nullable=False),
    sa.Column('subtitles', sa.JSON(), nullable=False),
    sa.Column('audio_id', sa.String(length=36), nullable=True),
    sa.Column('image_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['audio_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('options',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'position')
    )
    op.create_index(op.f('ix_options_question_id'), 'options', ['question_id'], unique=False)
    op.create_table('practices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('level', sa.String(length=2), nullable=False),
    sa.Column('type_id', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('requested_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('request_key', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['question_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'request_key')
    )
    op.create_index(op.f('ix_practices_user_id'), 'practices', ['user_id'], unique=False)
    op.create_table('tokens',
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('digest')
    )
    op.create_index(op.f('ix_tokens_user_id'), 'tokens', ['user_id'], unique=False)
    op.create_table('occurrences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('exam_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('type_id', sa.String(length=64), nullable=True),
    sa.Column('level', sa.String(length=2), nullable=False),
    sa.Column('group_key', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('instruction', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.JSON(), nullable=False),
    sa.Column('import_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['question_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_occurrences_catalog', 'occurrences', ['level', 'type_id', 'status'], unique=False)
    op.create_index(op.f('ix_occurrences_exam_id'), 'occurrences', ['exam_id'], unique=False)
    op.create_index(op.f('ix_occurrences_group_key'), 'occurrences', ['group_key'], unique=False)
    op.create_index(op.f('ix_occurrences_import_id'), 'occurrences', ['import_id'], unique=False)
    op.create_index(op.f('ix_occurrences_question_id'), 'occurrences', ['question_id'], unique=False)
    op.create_table('practice_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('practice_id', sa.String(length=36), nullable=False),
    sa.Column('occurrence_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('chosen_option_id', sa.String(length=36), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chosen_option_id'], ['options.id'], ),
    sa.ForeignKeyConstraint(['occurrence_id'], ['occurrences.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('practice_id', 'occurrence_id'),
    sa.UniqueConstraint('practice_id', 'position')
    )
    op.create_index(op.f('ix_practice_items_practice_id'), 'practice_items', ['practice_id'], unique=False)
    op.create_table('quality_issues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('import_id', sa.String(length=36), nullable=False),
    sa.Column('occurrence_id', sa.String(length=36), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['import_runs.id'], ),
    sa.ForeignKeyConstraint(['occurrence_id'], ['occurrences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_issues_import_id'), 'quality_issues', ['import_id'], unique=False)
    op.create_table('wrong_questions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('occurrence_id', sa.String(length=36), nullable=False),
    sa.Column('wrong_count', sa.Integer(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['occurrence_id'], ['occurrences.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'occurrence_id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wrong_questions')
    op.drop_index(op.f('ix_quality_issues_import_id'), table_name='quality_issues')
    op.drop_table('quality_issues')
    op.drop_index(op.f('ix_practice_items_practice_id'), table_name='practice_items')
    op.drop_table('practice_items')
    op.drop_index(op.f('ix_occurrences_question_id'), table_name='occurrences')
    op.drop_index(op.f('ix_occurrences_import_id'), table_name='occurrences')
    op.drop_index(op.f('ix_occurrences_group_key'), table_name='occurrences')
    op.drop_index(op.f('ix_occurrences_exam_id'), table_name='occurrences')
    op.drop_index('ix_occurrences_catalog', table_name='occurrences')
    op.drop_table('occurrences')
    op.drop_index(op.f('ix_tokens_user_id'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_index(op.f('ix_practices_user_id'), table_name='practices')
    op.drop_table('practices')
    op.drop_index(op.f('ix_options_question_id'), table_name='options')
    op.drop_table('options')
    op.drop_table('materials')
    op.drop_table('users')
    op.drop_table('questions')
    op.drop_index(op.f('ix_question_types_category'), table_name='question_types')
    op.drop_table('question_types')
    op.drop_table('import_runs')
    op.drop_index(op.f('ix_exams_level'), table_name='exams')
    op.drop_table('exams')
    op.drop_table('assets')
    # ### end Alembic commands ###
